const STAFF_ROLES = ["ADMIN", "DOCTOR", "STAFF"];
const STAFF_STATUSES = ["ACTIVE", "SUSPENDED"];
const STAFF_SENIORITIES = ["Junior", "Senior", "Consultant"];

const STAFF_DEPARTMENTS = [
  "Accounts",
  "Administration",
  "Billing & Insurance",
  "Biomedical Engineering",
  "Cardiology",
  "Dental",
  "Dermatology",
  "Emergency",
  "General Medicine",
  "General Surgery",
  "Gynaecology",
  "Inpatient",
  "Information Technology",
  "Laboratory",
  "Maintenance",
  "Marketing",
  "Medical Records",
  "Nephrology",
  "Neurology",
  "Nursing",
  "Oncology",
  "Operation Theatre",
  "Orthopaedics",
  "Outpatient",
  "Paediatrics",
  "Pharmacy",
  "Pulmonology",
  "Radiology",
  "Security",
  "Stores",
];

const STAFF_DESIGNATIONS = [
  "INCHARGE WARD",
  "SR STAFF NURSE",
  "STAFF NURSE",
  "EXECUTIVE",
  "LAB TECH",
  "DENTIST",
  "PEDIATRICIAN",
  "DUTY DOCTOR",
  "PHARMACIST",
  "SUPERVISOR",
  "PATIENT CORDINATOR",
  "JR PHARMACIST",
  "NURSING SUPERINTENDENT",
  "RMO",
  "TR STAFF NURSE",
  "JR ACCOUNTANT",
  "ADMINISTRATOR",
  "WARD INCHARGE",
  "AT TECH",
  "NURSE AIDE",
  "SR EXECUTIVE",
  "JR. RADIOGRAPHER",
  "RESIDENTS",
  "IT SYSTEM ADMIN",
  "RESIDENT",
  "JR RADIOGRAPHER",
  "ORTHPEDICIAN",
  "Manager Marketing",
  "MRD INCHARGE",
  "Lab Technician",
  "BIOMEDICAL ENGINEER",
  "Sr Exe-Insurance & Billing",
  "RADIOGRAPHER",
  "GYNAECOLOGY",
  "BILLING EXECUTIVE",
  "MANAGER-BILLING",
  "Incharge OP Billing",
  "MAINTENANCE SUPERVISOR",
  "MARKETING EXECUTIVE",
  "SCRUB NURSE",
  "Asst. Manager",
  "TECHNICIAN",
  "INCHARGE-LAB TECH",
  "Dietitian",
  "Sr-Executive IP",
  "security guard",
  "Incharge-Radiography",
  "ICU-STAFF NURSE",
  "GENERAL PHYSICIAN",
  "RADIOLOGIST",
  "Incharge-OPD",
  "NURSING AIDE",
  "OT TECHNICIAN",
  "BUSINESS DEVELOPMENT MANAGER",
  "STORE ASSISTANT",
  "Sr. Executive",
  "PHARMACY In-Charge",
  "ASSISTANT MANAGER - ACCOUNTS",
  "PHARMA AIDE",
];

module.exports = { STAFF_ROLES, STAFF_STATUSES, STAFF_SENIORITIES, STAFF_DEPARTMENTS, STAFF_DESIGNATIONS };
